ToDoList-Interactive list
Lichapa/ToDoList pull request #6
Opened 2021-11-03 16:20 UTC by Lichapa

In this pull request, I have done the following:

- Added a new JavaScript file and imported it as a module.
-  Add event listener to the checkbox.
- Update the local storage with correct values upon user actions

2021-11-03 18:25 UTC, rotimiazeez requested changes
# Hi @Lichapa👍, 

### Good job so far!👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

### Kindly see to the changes below and you are ready for the next stage✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-03 18:25 UTC, rotimiazeez commented on src/index.js
> +        </div><i class="fas fa-ellipsis-v"></i></li>`;
- [ ] please note that on page reload I didn't the correct list value😢, I only get the initial value you have on the todo's🤔 Kindly create an array for your list item and make sure they are stored in your local storage after the page reloads 🙌.

2021-11-03 18:25 UTC, rotimiazeez commented on src/interactive.js
> +  return todos;
- [ ]  I think this will be better if you have it in a function, for example:
 let todosArr = [];
const setTodosArr = () => {
  if (JSON.parse(localStorage.getItem('todos'))) {
    todosArr = JSON.parse(localStorage.getItem('todos'));
  } else { all items are false }

2021-11-04 09:40 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Mphatso Lichapa, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
# OPTIONAL BUT RECOMMENDED
- [ ] Please see inline comments.
## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-04 12:01 UTC, merged